---

version: '2'

volumes:
   nginx:

services:
    nginx:
       build:
         context: "Dockerfiles/nginx/"
       hostname: "nginx"
       command: ['/usr/bin/supervisord']
       ports:
         - "80:80"
         - "443:443"
       volumes:
          - "nginx:/var/www"
